### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by nicbarbier** [symphonycms/members#172]
The project we're using this extension for requires a (optional) session timeout.

Basically, when logging in, the user should be able to chose wether or not to stay logged in when the browser closes/after a certain time. 
- Is this functionality already implemented somewhere (but not documented) ?
- Otherwise, could you suggest the best way to implement this without hacking the extension (too much)?

Cheers

**Comment by andrewminton** [comment]
Has any of the session work @designermonkey changed, made it into a release yet? https://github.com/symphonycms/symphony-2/wiki/Cookie-and-Session

Wondering if it's worth revisiting a config option for timeouts with members at all?

**Comment by brendo** [comment]
It's in `integration`, but it's not available in an official release yet.

**Comment by andrewminton** [comment]
I'm assuming members will also need an overhaul of it's session implementation to work with the Symphony integration branch? since much has changed and the checks for isLoggedIn() will no longer apply right?

**Comment by brendo** [comment]
Yes, I believe there was backwards compatibility changes with @designermonkey's work that would mean Members needs an update.

**Comment by DavidOliver** [comment]
Just checking: is this still the same, and do members always have to log in again two weeks after their first login? (My client has requested a 'remember me' option, but I'm not sure of the reason behind that request yet.)

**Comment by michael-e** [comment]
AFAIK, it's still the same. There is a "two weeks" constant in Symphony which is used for session timeout. But I think it will mean "two weeks after being last seen", which is two weeks of inactivity.

Remark: Honestly, I think that this is far too long. Nowadays, I would vote for a much smaller period. Rather sooner than later users must get used to "safe passwords" (i.e.: using password managers, allowing super-complicated passwords), and browsers should be built/configured to delete **all** data when being closed (which is just a dream, I know…). People's expectations ("remember me") are so far away from any (security-advised) good practice…

**Comment by nitriques** [comment]
> But I think it will mean "two weeks after being last seen", which is two weeks of inactivity.

It does.

> People's expectations ("remember me") are so far away from any (security-advised) good practice…

Agreed. We must build upon the default browsers settings, sadly. The two weeks period never bothered me, except the first day of day of work of the year (which is two weeks). I would make it 1 year sliding window. The creds are validated upon every request anyhow.

We could make it configurable. 'session' cookie (whatever how it's implemented in browsers) could be created with a config value.

**Comment by michael-e** [comment]
Shouldn't we close this issue?
