### ISSUE TITLE
members event password field

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/members#220]
As the password field consists of other possible fields like `fields[password][recovery-code]` would it be possible to have the event output for the validation work in a similar way?

```
<password>
    <recovery-code type="missing" message="Recovery Code is a required field."/>
</password>
```

I've had to do some very hacky stuff to get validation messages to display inline with the right fields, as they always populate under the password field when just looking for the node in the event xml.

**Comment by michael-e** [comment]
I am going to close this, because this discussion is long since dead.
