### ISSUE TITLE
Compatibility with Symphony 2.6

### ISSUE THREAD

**Issue by michael-e** [symphonycms/members#267]
I assume that Members is compatible with Symphony 2.6, but @brendo will know better. It it is, we should release a version which is marked as compatible (in the meta XML file).

**Comment by nilshoerrmann** [comment]
I'm currently updating a site to 2.6 and it seems to work fine so far (besides the incompatibility note in the backend).

**Comment by michael-e** [comment]
Bump. I don't see any issues, so let's release a new version! Should I send a PR?

**Comment by nitriques** [comment]
> Should I send a PR?

Yes, please do, with an updated meta.xml file please :)

**Comment by nitriques** [comment]
This has been fixed in #271
