### ISSUE TITLE
constant(): Couldn't find constant DateTimeZone::

### ISSUE THREAD

**Issue by bernardodiasc** [symphonycms/members#269]
In a fresh Symphony 2.6.2 install, with the latest Members from master branch, after create a section with members fields, I can't access the section page.

![screenshot-localhost 2015-08-21 10-27-44](https://cloud.githubusercontent.com/assets/131859/9409240/5fbcc384-47ef-11e5-85a8-f41af3a43935.png)

**Comment by bernardodiasc** [comment]
Continued testing here, after select options in the timezone field the error above gone. So this is not an issue. I think the `Available zones` should be a required field anyway.
![screenshot-localhost 2015-08-21 10-31-01](https://cloud.githubusercontent.com/assets/131859/9409287/c08b7980-47ef-11e5-950c-4229c45edf67.png)

**Comment by nitriques** [comment]
> I think the Available zones should be a required field anyway.

I think that choosing none should equal to all... no ?

**Comment by bernardodiasc** [comment]
Actually, there is not much sense in add this field and not define at least one Zone. Thats why maybe work better setting the select box as required.

**Comment by nitriques** [comment]
> there is not much sense in add this field and not define at least one Zone

I rather have it save all tz without any errors then getting an error. UX wize, it makes a big difference.
