### ISSUE TITLE
Fatal error on basic installation

### ISSUE THREAD

**Issue by Manaus** [symphonycms/members#270]
Hello,  
I set up a basic installation of Symphony 2.5.1 and Members 1.4
I want to make a login page, so after pasting the login form template and making changes as needed (```input name="fields[username]"```), I get this error:

    Symphony Fatal Error: Call to a member function getFieldHandle() on a non-object
    An error occurred in /Users/../Sites/sym251/extensions/members/lib/member.symphony.php around line 167

Do I have to attach specific events to the page? 
Thanks

**Comment by brendo** [comment]
Make sure you've selected your Members section from the Preferences page.

**Comment by Manaus** [comment]
Thanks Brendo, now it's working.

**Comment by brendo** [comment]
Glad to hear it :)
