### ISSUE TITLE
Error while managing roles

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/members#277]
It seems like the role manager incorrectly escapes table names when trying to change role permissions:

> ### Symphony Fatal Database Error: Incorrect table name ''
> 
> An error occurred while attempting to execute the following query
>
>     DELETE FROM ``sym_members_roles_forbidden_pages`` WHERE `role_id` = 1

In my case, I was editing the public role, giving full write access to an event.

**Comment by nilshoerrmann** [comment]
Removing the backticks in `class.role.php` fixes the issue. It seems like all calls to the `Symphony::Database()->delete` function feature additional backticks which looks like the result of an agressive search and replace action.

**Comment by nitriques** [comment]
See https://github.com/symphonycms/symphony-2/commit/29a70c15058a28d6fc43a86500122c072bce2c35

Ticks have been added in the delete method, no need to do it when calling the method.
