### ISSUE TITLE
Symphony Warning: Illegal string offset 'firstname'

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/members#280]
When we go in symphony to System Member roles, we see all our roles and the number of members for each role. When we click on the number link, so that we see the filtered members we get an error:

```
Symphony Warning: Illegal string offset 'firstname'
An error occurred in /data/sites/web/xxx/symphony/content/content.publish.php around line 129
124 foreach ($section->fetchFilterableFields() as $field) {
125 if (!$field->canPublishFilter()) {
126 continue;
127 }
128
129 $filter = $filters[$field->get('element_name')];
130
131 // Filter data
132 $data = array();
133 $data['type'] = $field->get('element_name');
```

We use the latest symphony and lastest members extension.
Firstname is the first field in the section, moving an other field first, causes the other field to be in the error.

 **EDIT: Block format**

**Comment by michael-e** [comment]
Confirmed, s.th. is broken here.

**Comment by wdebusschere** [comment]
I only have it with one site, but it's the site with the most members.

**Comment by michael-e** [comment]
I confiremed the issue on one site with > 2000 members, and a second one with only 100 members.

**Comment by nitriques** [comment]
@wdebusschere Can you try to add this after [this line](https://github.com/symphonycms/symphony-2/blob/2.6.x/symphony/content/content.publish.php#L122)

```php
if (!is_array($filters) {
    return;
}
```

The code can't do anything if the $_GET parameter is not an array.

**Comment by wdebusschere** [comment]
Then i get: Symphony Warning: Illegal string offset 'system:creation-date'

`169 'label' => __('System Modification Date')
170 )
171 );
172
173 foreach ($fields as $field) {
174 $filter = $filters[$field['type']];
175
176 // Filter data
177 $data = array();
178 $data['type'] = $field['type'];`

**Comment by nitriques** [comment]
Which line ?

**Comment by nitriques** [comment]
This should be fixed.
