### ISSUE TITLE
Confusion around Members cookie being set

### ISSUE THREAD

**Issue by pixelninja** [symphonycms/members#281]
As the title suggests, I'm a little bit stumped by the Members cookie, and how it relates to Symphony core cookies. 

My client's site isn't out of the ordinary, it uses the Members extension for user log in, and the client uses Symphony to manage everything. But they recently asked if the auto logout time could be reduced. I did some digging in Members and came across the `initialiseCookie()` function in `class.members.php` which seemed pretty self explanatory. I created my own time constant for 6 hrs, and replaced `TWO_WEEKS` with this.

But when I checked the cookies through the inspect tool, it wasn't there. There is a `PHPSESSID` cookie which seems to be anything Symphony related. That is, my Symphony session as well as my Members session combined. 

But looking at the above function, I would have expected to see a cookie labeled `sym-members` (default `cookie-prefix` set in the `manifest/config.php`).

Then I came across the `func.utilities.php` file within Symphony, and the function `cleanup_session_cookies()`. I have had to change the value within this function to my new constant, but now Symphony backend sessions are affected. Not ideal really.

What am I missing? Should the cookies not be separated so they are treated separately? Why is the `cleanup_session_cookies()` function combining everything into a single cookie?

Thanks in advance.

**Comment by twiro** [comment]
Have you read through [this issue](https://github.com/symphonycms/members/issues/172) here? Might at least clarify some things your struggling with, though I assume the irritating session/coookie-behaviour hasn't been fixed yet... maybe @brendo , @nitriques, @jonmifsud or @michael-e know more about this.

**Comment by michael-e** [comment]
Re-writing the session/cookie stuff is a major undertaking... Honestly, I don't expect it in Symphony 2.

**Comment by nitriques** [comment]
> I don't expect it in Symphony 2.

Neither should anybody, sadly. Maybe for other releases!

**Comment by michael-e** [comment]
Shouldn't we close this issue?
