### ISSUE TITLE
Member not found anymore after frontend_localisation extension update

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/members#282]
After updating the frontend_localisation 2.71. to 2.7.2 my existing members can't login anymore. Creating a new member + login of the new member works..

```
<member-login-info logged-in="no" result="error">
            <email label="Email" type="invalid" message="Member not found." message-id="105" />
            <password label="Password" type="invalid" message="Invalid Password." message-id="105" />
            <post-values>
                <email>info@xxxx.xx</email>
                <password>xxx</password>
            </post-values>

```

After downgrading the extensions, the users can login again

**Comment by nitriques** [comment]
Hum this is weird: https://github.com/DeuxHuitHuit/frontend_localisation/compare/2.7.1...2.7.2 Only a set call has been changed...

**Comment by wdebusschere** [comment]
I know, but if i do the update the members can't login anymore, reverting the update it works again, will try with my update mysqlserver again now.

**Comment by nitriques** [comment]
@wdebusschere do you have something in Symphony's log ? Do you have languages in the front end that are not installed in the backend ?

**Comment by wdebusschere** [comment]
no errors in php or symphony log
2.7.2 only has small changes:

Lang::set(FLang::getLangCode(), false); //with this line login with existing member doesn't work
Lang::set(FLang::getLangCode()); // changing to this line works..

**Comment by nitriques** [comment]
WTF.

**Comment by nitriques** [comment]
When you remove the 'false' do you have messages like this in your log ?
`The selected language, %s, could not be found. Using default English dictionary instead` ? Does all FE languages are installed in the backend ?

**Comment by wdebusschere** [comment]
Issue seems to be fixed after updating symphony, extensions..

**Comment by nitriques** [comment]
Hum, ok then! Feel free to re-open the issue.
