### ISSUE TITLE
Changing the password logs the member out

### ISSUE THREAD

**Issue by michael-e** [symphonycms/members#299]
This issue replaces #266.

If you use a frontend form for Member data including the Member password, you will — in most cases — attach the "Members: Update Password" filter to your Symphony event, which is supposed to log the Member in with the new password.

This actually works (so the page gets displayed); but on the following page request, the Member is logged out (and the session is deleted).

Aside No. 1: This issue has nothing to do with the "Reset password" event. Instead the issue arises with a native Symphony event (simply saving the password field).

Aside No. 2: @wdebusschere mentioned on Gitter that a member also gets logged out if you change a logged in member's password through the symphony admin. This behaviour is fine, IMHO.

It took me some time to understand the issue, so I will try to document this here. It may help to understand how Member login and cookie stuff work.

There are two functions in the Members extension which are interesting in our scenario:

* `SymphonyMember::login` is called by the "Members: Update Password" filter to log the Member in with the new password. The filter passes the cleartext (i.e. unhashed) password to the `login` function, so it sets the `$isHashed` parameter to `false`. The latter parameter will be passed like this to the `SymphonyMember::findMemberIDFromCredentials` function.
* `SymphonyMember::isLoggedIn` is always called early on every page load (so it will be called upon the mentioned *subsequent page request*). This function also calls `SymphonyMember::findMemberIDFromCredentials`, but here the `$isHashed` parameter will be `true`.

I am skipping the next steps. In the end, in both cases, `Cryptography::compare` will be called to compare a given password to the Member's password hash in the database. The mentioned `$isHashed` parameter will be passed as well.

Now the thing is: The `compare` function can compare a cleartext password to a saved password hash. But if hashing uses a random salt, you can never validate that two **different hashes** have been derived from the same password.

Why are the password hashes different on the subsequent page request, when `SymphonyMember::isLoggedIn` is called (and even if you save the old password as new password)? Simply because the `login` function sets the cookie using an outdated password hash (derived from the Member object that has been created before the password was changed).

So the solution is to refresh the Member object before attempting a login.

I will send a pull request.

**Comment by nitriques** [comment]
Wow thanks @michael-e for this detailed explanation!

**Comment by wdebusschere** [comment]
👍

**Comment by tiloschroeder** [comment]
thanks @michael-e +1
